name: "Build Nix package"

on:
  push:

jobs:
  export-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Linux Library
        run: nix build .#linux64 --print-build-logs --no-sandbox

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: result
        
  export-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Windows Library
        run: nix build .#windows64 --print-build-logs --no-sandbox
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: result