name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  export-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Linux Library
        run: nix build --print-build-logs --no-sandbox

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-lib
          path: result
        
  export-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Building Windows Library
        run: nix build .#x86_64-pc-windows-gnu --print-build-logs --no-sandbox
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-lib
          path: result